### ISSUE TITLE
Depreciate original mixin

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#10]
Seems superfluous now to have both the function and original mixin. The function is far more versatile and is easier to write.

**Comment by codingdesigner** [comment]
I think you're right. I was thinking it was there for people who are more comfortable with mixins, but that's kind of a crutch, right?

**Comment by scottkellum** [comment]
Functions are better, they should learn them. Lets get rid of it.

**Comment by adamstac** [comment]
If we do, don't forget that the classes mixin uses this https://github.com/scottkellum/modular-scale/blob/master/stylesheets/_modular-scale.sass#L208

**Comment by scottkellum** [comment]
I was about to delete it but then saw the classes mixin and the regular mixin next to each other. Might as well leave it in as they have a lot of similarities.

**Comment by codingdesigner** [comment]
It's still a bit vestigial. I'm still thinking of taking it out, and rewriting the classes mixin accordingly. Should be a pretty simple change.

**Comment by adamstac** [comment]
Yea, the classes mixin can get re-written accordingly to use the function instead.

**Comment by codingdesigner** [comment]
I went ahead and deprecated it. For now running the mixin will send a warning to the console, but still work.

**Comment by adamstac** [comment]
Which brings up a topic we should mention for extension devs, when to use @debug and @warn.

**Comment by scottkellum** [comment]
So many new things to learn.

**Comment by codingdesigner** [comment]
good point. I'd love to draft something on that. I'd be lost w/o @debug

**Comment by adamstac** [comment]
I have a start to a guide on if, for, each, while that has some uses of this in the code samples but nothing that dives into the subject. Take a peek at the read lists and feel free to add to them :)
