### ISSUE TITLE
How to use dual base-sizes instead of dual ratios

### ISSUE THREAD

**Issue by rizqinizamil** [modularscale/modularscale-sass#110]
Like title said, How to use dual base-sizes instead of dual ratios?

**Comment by scottkellum** [comment]
@rizqinizamil If you want base sizes of 12px and 16px write it like this: `$ms-base: 12px 16px`

Dual ratios will be removed in version 3.0 but double stranded scales (dual base-sizes) will stay.

**Comment by rizqinizamil** [comment]
Thank you for your respond.
I have another question, where I should put the breakpoints when I want to use `16px` for screen with `min-width: 60em` and `12px` for screen below it?

Thanks again.

**Comment by scottkellum** [comment]
@rizqinizamil This will be available in 3.0 but 2.x only allows you to adjust the ratio. I suggest you use relative units to do this in 2.x. I’d suggest you use relative units in general as they make it really easy to adjust your rendered base size of any text.

**Comment by rizqinizamil** [comment]
Ok. Thanks for your suggestion @scottkellum :)
