### ISSUE TITLE
Vertical rhythm

### ISSUE THREAD

**Issue by strarsis** [modularscale/modularscale-sass#115]
What scss module would work well with this for vertical rhythm?
It seems that modularscale already can do this on its own?
- [Compass Vertical Rhythm](http://compass-style.org/reference/compass/typography/vertical_rhythm/)
- [Sassline](https://sassline.com/)
- [vertical-rhythmic](https://github.com/pyrsmk/vertical-rhythmic)
- [Typesettings](http://typesettings.io/)

The different ms values per breakpoint must be taken into account, as ms-respond() does.

**Comment by scottkellum** [comment]
@strarsis You should be able to use this with other vertical rhythm plugins. I have no intention of adding 1st party support for vertical rhythm to this library. Some properties of the golden ratio allow vertical rhythm to happen naturally.

**Comment by olivierbossel** [comment]
Check out sugarcss.io that helps you use vertical rhythm and modular scale :)

**Comment by olivierbossel** [comment]
As well as a lot of others cool things!!

**Comment by olivierbossel** [comment]
As well as a lot of others cool things!!
