### ISSUE TITLE
documenting exponents

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#12]
As a side effect of the new calculation logic, an exponent function is built in.

exponent(5, 3) is a way of calculating 5^3=125

I guess it can go in a new section of the readme, but it doesn't seem to fit with the rest of the modular scale stuff.

**Comment by codingdesigner** [comment]
Probably the best place to document this within the modular scales project is in a comment block above the function. Eventually the proper home for generic functions like that might be in a library like Compass.

**Comment by scottkellum** [comment]
done
