### ISSUE TITLE
Issues with bower on multiple Windows machines

### ISSUE THREAD

**Issue by alanontheweb** [modularscale/modularscale-sass#122]
Hello there,

2 of my team members received the following error on separate Windows machines. It doesn't cause issues with Mac or Linux, as it seems related to the long-path character limitation of Windows. When the team runs "bower update", they receive the following error (and it breaks bower's updates of other components). Commenting out Modular Scale allows bower to run successfully.

Both machines are windows 10, with NPM 3.5.x and above.  

`bower modular-scale#~2.1.1             ECMDERR Failed to execute "git clone https://github.com/Team-Sass/modular-scale.git -b v2.1.1
 --progress . --depth 1", exit code of #128 Cloning into '.'... remote: Counting objects: 2950, done.         remote: Compressing ob
Resolving deltas: 100% (188/188), done. remote: Total 2950 (delta 188), reused 2922 (delta 181), pack-reused 0         Checking conn
ectivity... done. Note: checking out '57d6df3c3b318ff86eea38653e8d1f8f6640b105'.  You are in 'detached HEAD' state. You can look aro
und, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by performing another checkout.  If you want to create a new branch to retain commits you create, you may do so (now or later) by
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream-pipe-error-handling.js (Filename too long) error: unable to create file test-node-sass/node_modules/e
xpress/node_modules/connect/node_modules/multiparty/node_modules/readable-stream/test/simple/test-stream-readable-flow-recursion.js
(Filename too long) error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/no
de_modules/readable-stream/test/simple/test-stream-unshift-empty-chunk.js (Filename too long) error: unable to create file test-node
-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream/test/simple/test-stream2-pipe-e
rror-handling.js (Filename too long) error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modu
les/multiparty/node_modules/readable-stream/test/simple/test-stream2-pipe-error-once-listener.js (Filename too long) Checking out fi
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream2-readable-empty-buffer-no-eof.js (Filename too long) error: unable to create file test-node-sass/node
_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream/test/simple/test-stream2-readable-from-li
st.js (Filename too long) error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multipa
rty/node_modules/readable-stream/test/simple/test-stream2-readable-legacy-drain.js (Filename too long) error: unable to create file
test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream/test/simple/test-strea
m2-readable-non-empty-end.js (Filename too long) error: unable to create file test-node-sass/node_modules/express/node_modules/conne
ct/node_modules/multiparty/node_modules/readable-stream/test/simple/test-stream2-readable-wrap-empty.js (Filename too long) Checking
error: unable to create file test-node-sass/node_modules/grunt-sass/node_modules/node-sass/libsass/sass-spec/spec/scss/almost_ambigu
error: unable to create file test-node-sass/node_modules/grunt-sass/node_modules/node-sass/libsass/sass-spec/spec/todo/css_closing_l
error: unable to create file test-node-sass/node_modules/grunt-sass/node_modules/node-sass/libsass/sass-spec/spec/todo/newlines_remo
fatal: cannot create directory at 'test-node-sass/node_modules/grunt-sass/node_modules/node-sass/node_modules/mocha/node_modules/glo
b/node_modules/minimatch/node_modules/lru-cache': Filename too long warning: Clone succeeded, but checkout failed. You can inspect w
hat was checked out with 'git status' and retry the checkout with 'git checkout -f HEAD'
Additional error details:
Cloning into '.'...
remote: Counting objects: 2950, done.
remote: Compressing objects: 100% (2399/2399), done.
Receiving objects: 100% (2950/2950), 6.34 MiB | 1.64 MiB/s, done.
Resolving deltas: 100% (188/188), done.
remote: Total 2950 (delta 188), reused 2922 (delta 181), pack-reused 0
Checking connectivity... done.
Note: checking out '57d6df3c3b318ff86eea38653e8d1f8f6640b105'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream-pipe-error-handling.js (Filename too long)
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream-readable-flow-recursion.js (Filename too long)
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream-unshift-empty-chunk.js (Filename too long)
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream2-pipe-error-handling.js (Filename too long)
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream2-pipe-error-once-listener.js (Filename too long)
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream2-readable-empty-buffer-no-eof.js (Filename too long)
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream2-readable-from-list.js (Filename too long)
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream2-readable-legacy-drain.js (Filename too long)
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream2-readable-non-empty-end.js (Filename too long)
error: unable to create file test-node-sass/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-
stream/test/simple/test-stream2-readable-wrap-empty.js (Filename too long)
error: unable to create file test-node-sass/node_modules/grunt-sass/node_modules/node-sass/libsass/sass-spec/spec/scss/almost_ambigu
ous_nested_rules_and_declarations/expected_output.css (Filename too long)
error: unable to create file test-node-sass/node_modules/grunt-sass/node_modules/node-sass/libsass/sass-spec/spec/todo/css_closing_l
ine_comment_end_with_compact_output/expected_output.css (Filename too long)
error: unable to create file test-node-sass/node_modules/grunt-sass/node_modules/node-sass/libsass/sass-spec/spec/todo/newlines_remo
ved_from_selectors_when_compressed/expected_output.css (Filename too long)
fatal: cannot create directory at 'test-node-sass/node_modules/grunt-sass/node_modules/node-sass/node_modules/mocha/node_modules/glo
b/node_modules/minimatch/node_modules/lru-cache': Filename too long
warning: Clone succeeded, but checkout failed.`

Can you provide any support for this issue? 

Thanks!

**Comment by rootical** [comment]
`git config core.longpaths true` should help

**Comment by andrejpavlovic** [comment]
Why include test folders _test-node-sass_ and _test-compass_ in the bower package?

**Comment by scottkellum** [comment]
@andrejpavlovic that would be a mistake, sorry, I don’t use Bower to manage my packages. I’ll audit all the things for the 3.0 release.

**Comment by vdecree** [comment]
I am getting the same error on Windows, @rootical suggestion failed to help me get it working. If anyone has anymore suggestions, it'd be appreciated.

**Comment by alanontheweb** [comment]
It didn't work for us either. When is 3.0 being released? I think the issue could be remedied if those includes were no longer there. As of right now, modular scale is breaking our bower update on windows, and we have to disable it temporarily for packages to download properly. Clearly not a solution.

**Comment by scottkellum** [comment]
Y’all are welcome to PR a patch if you can find a bug fix and I can push and update to 2.x. I don’t have much time to work on this at the moment but will always make time for community patches.

Things will be out when they are ready.

**Comment by scottkellum** [comment]
Appreciate the patch @chrisuehlinger! Should be merged and ready to go @alanontheweb, let me know if this fixes the issue.

**Comment by alanontheweb** [comment]
Thanks guys! @scottkellum @chrisuehlinger I'll let you know.

**Comment by alanontheweb** [comment]
Hey guys, both the Windows users on my team have confirmed it's working! Thanks again for the help. @chrisuehlinger @scottkellum

**Comment by vdecree** [comment]
Thank you for this. It's much appreciated.
