### ISSUE TITLE
Responsive Scales

### ISSUE THREAD

**Issue by christianmagill** [modularscale/modularscale-sass#123]
I love the idea of this library but I'm getting tripped up with the responsive scales.

It seems to me that regardless of the ratio or the sizes selected the values start out at the same size and have to work there way up to the difference.

I've made an example here:

http://www.sassmeister.com/gist/69d08ddd7e085e2ff09b22beb1659969

Regardless of the $ms-range which controls the responsiveness, shouldn't the h1, and p font-sizes be drastically different even at the smallest size?

From what I am seeing at around 300px they are exactly the same.

Thanks for any help.

**Comment by scottkellum** [comment]
Hi @christianmagill,

The thing that defines the size contrast in your scale is the ratio. Currently you have it set up with a ratio of `1` to `1.5` and you’re not seeing a difference between `h1` and `p` sizes because a ratio of `1` indicates no scaling.

So the ratio is a multiplier, `1 * $base` is going to result in the same value, `$base`, but `1.5 * $base` will result in a higher number.

I recommend starting at a ratio of around `1.15` or `1.2`:

``` sass
$ms-range: 
  1.2 20em,
  1.5 60em;
```

**Comment by christianmagill** [comment]
Thanks for the insight! So does this ratio then negate the ratio set by $ms-ratio?

Is there any way to maintain the main ratio but increase the overall size of the items as the browser expands?

**Comment by scottkellum** [comment]
> Thanks for the insight! So does this ratio then negate the ratio set by $ms-ratio?

Yes it does override `$ms-ratio`

> Is there any way to maintain the main ratio but increase the overall size of the items as the browser expands?

If you are using relative units, change the font size on your `body` element. This plugin uses [this method for scaling](http://madebymike.com.au/writing/precise-control-responsive-typography/) but you can scale based on breakpoint as you see fit.

**Comment by scottkellum** [comment]
@christianmagill did this resolve this issue for you? I’m going to close it out.

**Comment by christianmagill** [comment]
Yes, I may create a similar mixin that accepts a multiplier to get what I'm after, but I do like the ability to change the ratio as needed as well. Thanks!
