### ISSUE TITLE
Deprecated Rules

### ISSUE THREAD

**Issue by dawidvdh** [modularscale/modularscale-sass#126]
I have recently upgraded to node-sass 3.7.0 and now recieve the following when i compile with webpack:

Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
WARNING: Unfortunately, you need Compass to use non-integer exponents

Backtrace:
    node_modules/modularscale-sass/stylesheets/modular-scale/_pow.scss:13, in function `ms-pow`
    node_modules/modularscale-sass/stylesheets/modular-scale/_calc.scss:15, in function `ms-calc`
    node_modules/modularscale-sass/stylesheets/modular-scale/_function.scss:7, in function `ms`
    stdin:9

Any Help is Greatly Appreciated.

**Comment by scottkellum** [comment]
@dawidvdh Are you using non-integer values in your `ms()` functions? They will not work and have not worked in this version of modular-scale. If you previously had Compass compile your Sass then that’s why it worked before.

3.x will be better here. I feature detect for a pow function so you can add on [mathsass](https://github.com/terkel/mathsass/) if you need to use non-integer exponents.

**Comment by scottkellum** [comment]
Closing as this thread seems to be inactive. If you are still having this issue please reopen @dawidvdh
