### ISSUE TITLE
modular-scale gem outputting different values than modularscale-sass node package

### ISSUE THREAD

**Issue by rich-martinez** [modularscale/modularscale-sass#129]
I recently switched from using the gem (version 2.0.6) to using the node package (2.1.1), and that is when I noticed this difference.

With these MS variables defined: 

```
$ms-base: 1rem 1.75rem;
 $ms-ratio: $minor-second;
```

Using the gem I get the following:

```
@debug ms(-4);  //DEBUG: 0.77248rem
@debug ms(-3);  //DEBUG: 0.82397rem
@debug ms(-2);  //DEBUG: 0.87891rem
@debug ms(-1);  //DEBUG: 0.9375rem
@debug ms(0);   //DEBUG: 1rem
@debug ms(1)    //DEBUG: 1.04426rem
```

Using the node package I get the following:

```
@debug ms(-4);  //DEBUG: 0.87891rem
@debug ms(-3);  //DEBUG: 0.91781rem
@debug ms(-2);  //DEBUG: 0.9375rem
@debug ms(-1);  //DEBUG: 0.97899rem
@debug ms(0);   //DEBUG: 1rem
@debug ms(1);   //DEBUG: 1.04426rem
```

Does it has something to do with the #75 , since only negative values seem to be affected?  If so, is there a work around? What exactly is causing the problem? I was thinking it had something to do with ms-list based on the issue, but...

Any help would be appreciated.

**Comment by scottkellum** [comment]
Should be fixed, 3.0 is a major overhaul
