### ISSUE TITLE
Error on including scss

### ISSUE THREAD

**Issue by agileapricot** [modularscale/modularscale-sass#13]
I get the following error when simpliy including an @import to  'modular-scale.scss'; 

![error](http://dl.dropbox.com/u/497583/screenshots/SCSSerror.png)

**Comment by scottkellum** [comment]
Make sure you are running the latest version of Sass. That error can occur on versions before writing of lists was supported.

**Comment by agileapricot** [comment]
Hi. I installed the gem instead and that works for me. I am running sass 3.1.7.

Off topic a bit but what is the easiest to output a list like this one? So I can see the potential sizes I can choose from given my set of values?

http://modularscale.com/scale/?px1=16&px2=300&ra1=1.618&ra2=0

Awesome gem btw. I was about to write my own but it wouldn't have come close to this.

**Comment by codingdesigner** [comment]
Thanks for finding this. We develop using .sass primarily and it looks like there were some errors in converting it to .scss. 

I've just made an update here in the repo to make a fix. Try using this new version, and let us know if you still have problems. 
https://github.com/scottkellum/modular-scale/blob/d133d1c0e44c9cac0154b5fbf62eaf169046ab5b/stylesheets/_modular-scale.scss

**Comment by codingdesigner** [comment]
The only way I know of to output a list is to use  @debug, which show's it's output in the terminal. 

@debug ms(1)
@debug ms(2)
etc

**Comment by scottkellum** [comment]
Should we just include the .sass version for now? If the syntax is actually holding this back, most people are going to be linking this file not editing it.

**Comment by codingdesigner** [comment]
I'm actually leaning towards just including scss. :) My personal preference is for sass, but compass and many other gems are using scss so I'm leaning that way for consistency's sake.

**Comment by agileapricot** [comment]
New error with the updated file i'm afraid. Btw I was wrong about the gem working for me, I was looking at the wrong bit. It wasn't working.

![New error](http://dl.dropbox.com/u/497583/screenshots/newerror-mc.png)

**Comment by codingdesigner** [comment]
Ahh, Same problem as before, but I had I missed a couple other empty lists. I think I have them all now. 
https://github.com/scottkellum/modular-scale/blob/master/stylesheets/_modular-scale.scss

**Comment by agileapricot** [comment]
Great. That works a treat :)
