### ISSUE TITLE
Would be useful to include sass for the example `See a responsive modular scale in action.`

### ISSUE THREAD

**Issue by musm** [modularscale/modularscale-sass#130]
Would be helpfull as documentation to include the SASS for the example "[See a responsive modular scale in action.](http://lab.scottkellum.com/ms-respond.html)" .

**Comment by gabelloyd** [comment]
This link seems to no longer work, but [this file in the repo](https://github.com/modularscale/modularscale-sass/blob/2.x/test-compass/sass/style.scss) is equally helpful as a reference.

**Comment by scottkellum** [comment]
Updated in the readme
