### ISSUE TITLE
Non-integer values with libsass

### ISSUE THREAD

**Issue by gfellerph** [modularscale/modularscale-sass#133]
Any chance of getting doubles to work in libsass?

The following line:
`font-size: ms(1.5, $golden);`

generates the same output as this one:
`font-size: ms(2, $golden);`

**Comment by gfellerph** [comment]
Never mind, got it to work by installing https://github.com/terkel/mathsass and importing it before the modularscale-sass node_module. Think this might help someone else in the same situation (modularscale-sass checks the existence of the **pow(x, y)** function and defaults back to integers only if it does not exist. mathsass provides this function).

For the record, I'm using the following setup:

- Windows 10 64bit
- Node 6.2.2
- Gulp 3.9.0
- gulp-sass 2.3.2
- mathsass 0.9.5
- modularscale-sass 2.1.1

Thanks for the awesome library!

**Comment by strarsis** [comment]
This may be also related: https://github.com/modularscale/modularscale-sass/issues/112
