### ISSUE TITLE
v2.x and v3.x

### ISSUE THREAD

**Issue by strarsis** [modularscale/modularscale-sass#135]
@scottkellum: With version 2.x I have issues with pow(...) (see https://github.com/modularscale/modularscale-sass/issues/112).

Version 3.x doesn't seem to be ready/stable yet and is unreleased, 
also it seems that in v3.x ms-respond(...) sometimes doesn't output anything for 1 as first argument.
More examples would be nice, like how to set the margins for paragraphs or defining a matching line-height.

**Comment by mabar** [comment]
It seems like the package developer is no more active. I will probably rewrite 3.x version in next months.

**Comment by scottkellum** [comment]
@mabar feel free to submit PRs, lots of life stuff happening in the past year, apologies for the delay.

**Comment by scottkellum** [comment]
I’m launching tonight @strarsis @mabar
