### ISSUE TITLE
Undefined operation: pow

### ISSUE THREAD

**Issue by christianhg** [modularscale/modularscale-sass#137]
Trying out v3 (with webpack and getting:

```
Undefined operation: "pow(1.61803, 0) times 18px".
in /foo/node_modules/modularscale-sass/stylesheets/modularscale/_function.scss (line 15, column 25)
```

It looks like the `pow` function is not defined anywhere.

**Comment by scottkellum** [comment]
Thanks, looking into it

**Comment by scottkellum** [comment]
Sorry about that @christianhg and thanks for pointing these issues out! Should be fixed now.

**Comment by christianhg** [comment]
No problem at all! Good job on fixing it so promptly!
