### ISSUE TITLE
ms(0) returns the 1st value in the scale instead of the 0th

### ISSUE THREAD

**Issue by mixxorz** [modularscale/modularscale-sass#138]
Code
```scss
$modularscale: (
  base: 16px,
  ratio: 1.5
);

@debug ms(-1);
@debug ms();
@debug ms(0);
@debug ms(1);
@debug ms(2);
```

Output
```
DEBUG: 11px
DEBUG: 24px
DEBUG: 24px
DEBUG: 24px
DEBUG: 36px
```

**Comment by scottkellum** [comment]
Thanks @mixxorz, I’m unable to replicate this issue, can you provide more info as to how you are running modular scale? Are you using ruby-sass, Compass, libsass, eyeglass, node-sass, and what version numbers?

**Comment by wagich** [comment]
I'm getting the same results using a minimal repro with the following gulpfile
```` js
gulp.task("test", function() {
	return gulp.src("test.scss")
        .pipe(sass());
});
````

Running nodejs 6.9.1 and gulp-sass@3.1.0 which uses node-sass@4.2.0

**Comment by scottkellum** [comment]
Thanks, I am able to replicate and will fix soon

**Comment by scottkellum** [comment]
Fixed, thanks y’all for the report!

**Comment by mixxorz** [comment]
Wow! Thanks for the really fast response and fix!
