### ISSUE TITLE
Throws warning "Unescaped multiline strings are deprecated and will be removed in a future version of Sass."

### ISSUE THREAD

**Issue by hansspiess** [modularscale/modularscale-sass#144]
When used with jekyll, ms throws the following:

> DEPRECATION WARNING on line 21, column 12 of /site-jekyll/node_modules/modularscale-sass/stylesheets/modularscale/_pow.scss:
Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
To include a newline in a string, use "\a" or "\a " as in CSS.

Althrough this is no blocker, maybe it can be fixed.

**Comment by scottkellum** [comment]
Thanks! should be fixed now
