### ISSUE TITLE
adjust-leading-to

### ISSUE THREAD

**Issue by strarsis** [modularscale/modularscale-sass#149]
Is there an equivalent to `adjust-leading-to` in [Compass Vertical Rhythm](http://compass-style.org/reference/compass/typography/vertical_rhythm/)?

**Comment by scottkellum** [comment]
Thanks for the issue but I have no plans to implement this or anything similar at this time. While modular scales are very helpful in typesetting the scope of this project is to be used as a ruler not build it as a typesetting tool. I’m working on another project to address typesetting but if you’re a big fan of vertical rhythm you might be disappointed as I’ve never really cared for managing it. If I can think of a reasonable way to retain a baseline grid I may fold it into that project but it’ll probably be managed with CSS custom properties, JavaScript, and/or CSS Houdini as opposed to Sass.
