### ISSUE TITLE
$base-size 16px or 1em instead of 14px

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#15]
The default $base-size is currently 14px. The browser default is usually 16px.

Should we re-evaluate this default? 1em or rem is also a good candidate. Rem would be ideal because it IS the actual base font size but there isn’t enough browser support.

**Comment by codingdesigner** [comment]
14px is arbitrary. I like Rem, but I don't think it's time to support it. I think we should set it to 16px. It's much easier to convert px to ems than the other way around when the context shifts.

**Comment by scottkellum** [comment]
done: https://github.com/scottkellum/modular-scale/commit/39e2bc1d36fdbd91b7cb1663d9bd57e401cf909c
