### ISSUE TITLE
Combine breakpoints with threads

### ISSUE THREAD

**Issue by koko236** [modularscale/modularscale-sass#154]
Is it possible to combine breakpoints and threads? Ie. to have more than one thread defined for common breakpoints. Is so how should we use it? 
1. Is there a convention for defining threads with breakpoints?
2. Is there a way to specify thread in ms-respond call?

**Comment by koko236** [comment]
Ok, for those wondering about this later. You can define whole separate configs, eg. `$modular-scale-A`,` $modular-scale-B` and refer to them in ms-respond using third param, eg. `ms-respond(font-size, 1, $modular-scale-A);`.

**Comment by scottkellum** [comment]
Did you figure this out @koko236 ? Breakpoints are types of threads so in a sense they are already combined. If you wish to change the thread per breakpoint you will have to specify the Sass map you wish to use as the 3rd argument in the mixin like you stated.

**Comment by koko236** [comment]
@scottkellum I think so. For each thread I made a separate config object each with the breakpoints defined and I pass appropriate one as the third parameter to the `ms-respond()` call. So the breakpoints are defined INSIDE each thread.
