### ISSUE TITLE
Disable px rounding option

### ISSUE THREAD

**Issue by dnwhte** [modularscale/modularscale-sass#156]
Can you please add a settings option to disable the pixel rounding?

**Comment by scottkellum** [comment]
@danwhite85 Can you give me a use case? My guess would be high resolution displays so would rounding to 1/4th or 1/8th of a pixel be better?

**Comment by dnwhte** [comment]
Hi @scottkellum, we have some things that depend on the original unrounded pixel values. We also use PostCSS to convert our pixel values into rems.

An option to disable rounding or choose your own rounding would be great.

**Comment by scottkellum** [comment]
Fixed!
