### ISSUE TITLE
Output calculation as rem value

### ISSUE THREAD

**Issue by johnstonian** [modularscale/modularscale-sass#157]
I'm not sure this is an issue per se, but rather a feature request/question

Is there a way to ask for rem output when needed?

There are certain cases in which I'd like to be able to add a padding or margin value that is rem based instead of em based. Using ms(3) for example gives me the corresponding em value. Would be great if there was an option for something like ms(3, [em, rem, px]), with default always em unless specified.

Love this project btw, thank you for this!

**Comment by scottkellum** [comment]
Yup you can do this

In your settings use the units you want to use for the base, it takes any units so you can use miles if you want to:

```sass
$modularscale: (
  base: 1rem,
  ratio: 1.5
);
```

Let me know if you need anything else

**Comment by johnstonian** [comment]
Thank you @scottkellum! I should have asked about this a long time ago. Works like a charm!
