### ISSUE TITLE
Both regular and non-conflict ms functions are returning raw output

### ISSUE THREAD

**Issue by lmartins** [modularscale/modularscale-sass#159]
Hi,

Recently the library stopped working for me, and inspecting the generated CSS I've noticed that instead outputting a px value, the generated CSS now looks like this:

```css
font-size: ms-round-px(4.3984rem);
```

This happens using both `ms` and `ms-function`.

**Comment by jmrieger** [comment]
Seconded this issue. We saw this pop up in our builds today.

**Comment by leptest** [comment]
Same issue.  Seemed to break from version `3.0.6` ->`3.0.7`

**Comment by buddye** [comment]
yea looks like  `modularscale-sass/stylesheets/modularscale/_function.scss` still calls it.
I had to manually import the latest release and edit line 15 of _function.scss:
`@return ms-pow($ratio, $v) * $base;`

**Comment by scottkellum** [comment]
Sorry I didn’t realize people were using that as a standalone function as I didn’t document it as a feature. I will add it back in and plan better for phasing it out.

**Comment by scottkellum** [comment]
Sorry about that y’all and thank you for alerting me to it! It’s fixed now in v3.0.8

**Comment by leptest** [comment]
Thanks for the quick reply and fix @scottkellum
