### ISSUE TITLE
Push new gem

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#16]
Adam, can you push the new gem? Can you also add @canarymason and I so we can push new gems?

Thanks!

**Comment by adamstac** [comment]
I don't think it's a matter of me adding, it's a matter of your creds in the [gemspec](https://github.com/scottkellum/modular-scale/blob/master/modular-scale.gemspec) matching your rubygems user

**Comment by adamstac** [comment]
In the meantime:

```
adamstacoviak@AS-MBP-i7 [12:56:05] [~/Code/OS/sass/modular-scale] [master]
-> % rake gem:build
(in /Users/adamstacoviak/Code/OS/sass/modular-scale)
  Successfully built RubyGem
  Name: modular-scale
  Version: 0.0.5
  File: modular-scale-0.0.5.gem
adamstacoviak@AS-MBP-i7 [12:56:14] [~/Code/OS/sass/modular-scale] [master]
-> % rake gem:release
(in /Users/adamstacoviak/Code/OS/sass/modular-scale)
  Successfully built RubyGem
  Name: modular-scale
  Version: 0.0.5
  File: modular-scale-0.0.5.gem
Pushing gem to https://rubygems.org...
Successfully registered gem: modular-scale (0.0.5)
```

**Comment by scottkellum** [comment]
ok, well we should be good when this is pushed… at least my name and email match up with rubygems.

**Comment by adamstac** [comment]
http://rubygems.org/gems/modular-scale

**Comment by scottkellum** [comment]
Awesome! you rock @adamstac

**Comment by adamstac** [comment]
Word, happy to help sir :)

**Comment by scottkellum** [comment]
@adamstac looks like you can add me here: http://help.rubygems.org/kb/rubygems/supporter-faq scott@scottkellum.com

I just updated lists and better unicode support.

**Comment by scottkellum** [comment]
Pushed 1.0.rc1!!!

**Comment by codingdesigner** [comment]
With @snugug's update to sassy-math I didn't need to reroll anything. Let's test the 1.0 rc while we get the site together, and then release.
