### ISSUE TITLE
Removal of ms-round-px causes build failure

### ISSUE THREAD

**Issue by eburton** [modularscale/modularscale-sass#160]
Most recent release removed the ms-round-px function, but there is still a ref to the function here:

https://github.com/modularscale/modularscale-sass/blob/ce76e5a60f1de2ddc273cc5050aa48e0e9a995e5/stylesheets/modularscale/_function.scss#L15

**Comment by scottkellum** [comment]
Oof I really bungled this release. Thank you for the issue and I will fix as soon as I get home

**Comment by scottkellum** [comment]
@eburton Can you check again and see that your issue is fixed with whatever package manager or process for updating modular scale you use?

Thanks!

**Comment by eburton** [comment]
@scottkellum Looks good! Package manager is still picking up the old version, but I grabbed the latest commit and ran a test and it's not longer grumbling on SASS compilation.

Thanks for the quick response!

**Comment by scottkellum** [comment]
@eburton what install method/package manager do you use so that I can investigate?

Thanks! Glad it’s working better

**Comment by eburton** [comment]
@scottkellum just bower that seems to be misbehaving :)

`bower modularscale-sass#3.x.x mismatch Version declared in the json (v3.0.7) is different than the resolved one (3.0.8)`

**Comment by scottkellum** [comment]
Thanks I’m going to leave this open until I can test and ensure Bower is behaving and I’ve done things right on my end

**Comment by scottkellum** [comment]
@eburton I drafted a new release, let me know if that fixed your issue. Thanks for your patience.
