### ISSUE TITLE
Eyeglass v2.0.0 support

### ISSUE THREAD

**Issue by dotboris** [modularscale/modularscale-sass#162]
I upgraded eyeglass to v2.0.0 and got the following error:

```
The following modules are incompatible with eyeglass 2.0.0:
  modularscale needed eyeglass ^1.2.1
```

**Comment by scottkellum** [comment]
Thanks for the bug report! I’ll look into this later this weekend

**Comment by scottkellum** [comment]
Welp, life happens and am not finding the time to investigate this but bookmarked to fix when I have time to. Should be simple but I just can’t get to it now.

**Comment by dotboris** [comment]
For reference here's the actual breaking changes in v2 https://github.com/linkedin/eyeglass/issues/192

It seems like they dropped node older node version (v4 & v5)
