### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by SergioV85** [modularscale/modularscale-sass#164]
After updating the project to Angular 8, and node.js to v.10, I'm started receive a lot of errors like that:
`
DEPRECATION WARNING on line 34, column 5 of node_modules/modularscale-sass/stylesheets/modularscale/_function.scss: 
@elseif is deprecated and will not be supported in future Sass versions.
Use "@else if" instead.
   ╷
34 │     @elseif ($ms-base < nth($base,1)) {
   │     ^^^^^^^
   ╵
`

Please, take a look on it

**Comment by scottkellum** [comment]
Thanks for your patience, this has been fixed but I just pushed again as the last deploy didn’t catch everything. Hope that helps.
