### ISSUE TITLE
Facultative use of placeholders

### ISSUE THREAD

**Issue by Anahkiasen** [modularscale/modularscale-sass#17]
The modular-scale-classes is great but it can be a bit of an overkill, even more when you don't actually use the created classes in your HTML. For that I suggest the creating of a similar mixin, mudlar-scale-placeholder that would do pretty much the same :

``` sass
@for $i from 0 through $multiple
    %#{$class-slug}-#{$i}
      #{$property}: modular-scale($i, $base-size, $ratio)
```

Only the actual output would be a serie of placeholders, thus letting the code clean and leaving only the scales that are actually used.

**Comment by scottkellum** [comment]
Great idea, but using placeholder selectors would have to wait until 3.2 is out of beta.

The idea of generating classes is to better visualize values down the scale. In practice it would be easier and more flexible to write `ms($n)` to generate your values. Placeholder selectos do not generate a scale that the designer can look through.

That said, there might be a better way. How would you feel about just generating a list? That way you can `@warn` the list to see the values written out and call the `nth($list, $n)` or just `ms($n)` to write that value.

``` sass
@warn $modular-scale-list

// After looking at the warning, I like the 3rd value

.foo
  width: ms(3) // or nth($modular-scale-list, 3)
```

That way it provides the entire scale for the designer to look through without writing any CSS or HTML.

_implementation note:_ The list might need to be recalculated before warning. A mixin containing the recalculation along with the warning might be needed.

**Comment by Anahkiasen** [comment]
It's not really a matter of readability or usability, it's a matter of repetition. I'm using modular-scale a lot, for font-size/padding/margin and it leads to a lot of repetition of say `font-size: 16px`, everywhere on my CSS. By using placeholders to do something like that :

``` sass
// Using this
header
    @extend %ms2

// Instead of this
header
    font-size: ms(2)
```

I avoid a hugh amount of superflous CSS.

**Comment by scottkellum** [comment]
I think the best place for this would be in your own collection of mixins. Even though @canarymason and I use silent selectors extensively to keep our file size down, they aren’t in the release build of Sass.

The goal of this project is to provide basic modular scale calculations as a foundation for mixins like the one you posted. I agree the list calculations need to be rethought, but from a core functionality and generalize use case standpoint, not specific use cases.

I also worry that containing isolated `@extend` snippets like will generate more code for people as well. When frequently extending, selectors become duplicated and can bloat as much as when styles are duplicated. Writing your own selectors to `@extend` will allow you to bundle common styles and generate much better CSS.

Opened issue #18 to rethink lists.

**Comment by robwierzbowski** [comment]
For anyone homebrewing module scale placeholders, be aware that a placeholder defined outside of a media query can't be used inside of a media query. If you're adjusting font size a lot between breakpoints, using the functions or assigning a function value to a variable is probably a better solution.
