### ISSUE TITLE
Compilers and square root characters

### ISSUE THREAD

**Issue by Anahkiasen** [modularscale/modularscale-sass#19]
On line 19 of the main file you used a square root symbol `√`, and granted although neither Sass nor Compass themselves have a problem with it, a lot of the modern compilers and watchers out there (LiveReload, FireApp, Compass.app) seem to choke on it. 

As it is not really a crucial element of the sass file and could maybe be replaced by a simple V or a text formulation `square root`, is there any chance this character might be removed or modified ?

**Comment by scottkellum** [comment]
Thanks for the report, I will get on it. With all the talk of JS and C++ compilers it might be good for us to dumb down our character set anyways.

**Comment by scottkellum** [comment]
done!
https://github.com/scottkellum/modular-scale/commit/ccc799d611c1a538d1b9d37fcd6c438db66ea732
