### ISSUE TITLE
Choking on $golden variable

### ISSUE THREAD

**Issue by hatefulcrawdad** [modularscale/modularscale-sass#20]
I installed the gem added it to my config.rb file. When I started compiling, it was tripping up over the variable I had set of "$ratio: $golden;" I opted to just copy/past the stylesheet instead, but thought I'd call out this possible bug for you guys.

**Comment by scottkellum** [comment]
Thanks @zurbchris, at what point did you import modular-scale into your stylesheets? It needs to be imported at a higher point in the cascade than the instance you call your ratio. Also, if you can paste your console output here it would be a big help.

**Comment by hatefulcrawdad** [comment]
The importing of the stylesheet worked fine! It was when I tried to use the gem install implementation method that things got tripped up. Here's the output: `error scss/typography.scss (Line 5: Undefined variable: "$golden".)`

I had the variables at the top of typography.scss

**Comment by scottkellum** [comment]
Ah, you still need to @import modular scale in your style sheets after including it in your compass project.

`@import 'modular-scale';`

I will add this to the readme.

**Comment by hatefulcrawdad** [comment]
Doh!

**Comment by scottkellum** [comment]
No worries. the version here has some pretty cool new list features that haven’t been pushed to the gem just yet: https://github.com/scottkellum/modular-scale/commit/6d00b124f12b18611ba6bee6d6ea9d74d7603ca7

**Comment by stoplion** [comment]
Having the same problem
Added gem, added require 'modular-scale' to compass.rb, 

Within the same file tried both: @import "modular-scale" followed by a $ratio: $golden, and switching it up setting $ratio: $golden followed by @import "modular-scale". Both times got a `Undefined variable: "$golden".`
