### ISSUE TITLE
Refactor in Ruby

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#21]
Refactoring this in Ruby as a Compass plugin is going to provide a significant speed increase as well as increase accuracy. Downside: those not using Compass will have difficulty using this.

If we write this correctly it will not have to even be included in a stylesheet.

**Comment by codingdesigner** [comment]
I think the speed is worth it. I find myself hard-coding the results from
ms because of the lack of speed. There may be a way to work w/o compass,
but let's build the compass version first.

**Comment by codingdesigner** [comment]
I got list sorting in Ruby working last night and it seems a lot faster already. I'll get a few more features into ruby this weekend and then push.

**Comment by codingdesigner** [comment]
ok. moved all the math logic into Ruby now. it's hot shit fast now. Next up is moving the switching logic to Ruby. I doubt that will give us a speed improvement, but it should allow us to remove the need to include our partial.

**Comment by scottkellum** [comment]
Dude that’s awesome. Sometime I would love a walkthrough of this.

**Comment by codingdesigner** [comment]
Certainly. If you check the code right now you'll see almost all of Sassy math in there. I'm using some of it, and the rest as reference. Currently debating whether to make it a dependency. Thoughts on that?

**Comment by scottkellum** [comment]
Pretty easy to call a dependency in Sass, might as well just do it, especially when no style sheets needs to be @imported.

Will dig through it, still getting hung up on the little differences between Sass and Ruby. 

---

Scott Kellum
scott@scottkellum.com
(347) 422-7572

scottkellum.com

**Comment by codingdesigner** [comment]
We had some problem requiring the Fraction gem in Breakpoint. Something to do with different versions of Ruby. Since Math requires Fraction I want to test a bit before I make the requirement.

**Comment by codingdesigner** [comment]
This is nearly ready. I've decided to add Sassy Math as a dependency, but against moving the _entire_ thing to Ruby, at least for now. We aren't getting any more speed benefits, and as far as I can tell we lose the ability to set default variables.   This will be easier to maintain too, since neither of us are really ruby guys. 

You can test it now if you like. I think all that's left is to build the gem and push.

**Comment by scottkellum** [comment]
Brilliant, really brilliant. This is awesome.

**Comment by scottkellum** [comment]
Planning to review, clean up, and publish Friday.

**Comment by codingdesigner** [comment]
Sorry to drop off. I've been sick this week. I'd love a review, but I can handle the rest. I still need to move the ruby stuff from the config.rb to the gem definition.

**Comment by scottkellum** [comment]
Cool. My girlfriend is away this weekend so I have all weekend for this stuff.

Was thinking of bumping up to v1.0 and generating some more buzz around this. Also ping Zurb about this and send a pull request to integrate this properly. Currently their implementation seems a little weird but I haven’t dug too deep into it.

Also I was having a few Ruby issues on my machine. I may need to work through some of that to get gems installing in the right place.

Do what you feel up to, I will be available tomorrow night and all weekend to jam on this stuff.

**Comment by codingdesigner** [comment]
Ok. I'll try to finish my cleanup before the weekend. There's not too much to do there. Then you can do a review, we can address anything you find, and release on Monday. I was also thinking this was time for a 1.0.

**Comment by scottkellum** [comment]
Singularity is going beta this weekend. Maybe we can sync the releases up or even get a dedicated site for modular scale?

**Comment by codingdesigner** [comment]
awesome new about singularity! Yes, let's sync up. How about we hold on announcing the releases for a week or so while we set up the site(s)?

**Comment by scottkellum** [comment]
modular-scale.com and modularscal.es are now ours.

**Comment by codingdesigner** [comment]
I'm about to register scottkellumisawesome.com and noseriouslyscottkellumisawesome.com

**Comment by codingdesigner** [comment]
The timing is perfect for me. I have a couple talks coming up NYC on 7/21 and DC on 7/27 and having these releases by then will be very cool.

**Comment by codingdesigner** [comment]
@scottkellum I just did my own review and pushed. I've moved all the Ruby to the extension definition, rewrote the readme, and added a changelog. I would have pushed an alpha, but I can't. Which brings me to...

@adamstac We need you to add us as contributors on rubygems or we're going to keep bugging you for pushes. :) I looked up how to do it.

`gem owner --add mason@canarypromo.com`
`gem owner --add scott@scottkellum.com`
http://help.rubygems.org/kb/gemcutter/gem-ownership

**Comment by adamstac** [comment]
Word. I though having the emails in the Gemspec match you users email did the trick. I'll add you fellas tomorrow. 

Sent via iPhone4

**Comment by scottkellum** [comment]
Awesome @canarymason I am around if you want to plow through anything together. Was having trouble getting the gem to build with the sassy-math dependency. but other than that it looks solid.

Using the alpha extension to force rubygems to install using --pre? Was thinking about rc1 but alpha is good for that reason.

**Comment by codingdesigner** [comment]
hmm. I used the latest sassy-math and it built fine for me. once @adamstac adds me I can push to rubygems and we can test that verison

**Comment by scottkellum** [comment]
Might just be me. My ruby version is messed up on both of my computers. Having trouble finding gems after installing them.

**Comment by adamstac** [comment]
Sorry fellas, I tried to take care of this over the weekend and this is what I got then.

```
adamstacoviak@AS-MBP-i7 [03:54:16] [~/Code/OS/sass/modular-scale] [master]
-> % gem owner -a mason@canarypromo.com      
ERROR:  While executing gem ... (Gem::CommandLineError)
    Please specify a gem name on the command line (e.g. gem build GEMNAME)
```

Not sure what the issue is.

**Comment by codingdesigner** [comment]
@adamstac I did a little more digging, and I think you need to tell that command which gem you're changing the owners for. So you'll need to rebuild the gem since it's not in the repo, and then run: 

`gem owner modular-scale-1.0.alpha.gem  --add mason@canarypromo.com`

sorry to bug you about this.

**Comment by scottkellum** [comment]
@adamstac try this:

`gem owner my_gem -a foo@example.com`

**Comment by scottkellum** [comment]
```
gem owner -a mason@canarypromo.com modular-scale
gem owner -a scott@scottkellum.com modular-scale
```

**Comment by adamstac** [comment]
Score! https://rubygems.org/gems/modular-scale

```
adamstacoviak@AS-MBP-i7 [11:43:57] [~/Code/OS/sass/modular-scale] [master]
-> % gem owner -a mason@canarypromo.com modular-scale
Pushing gem to https://rubygems.org...
Owner added successfully.
Pushing gem to https://rubygems.org...
Owners for gem: modular-scale
- mason@canarypromo.com
- adam@adamstacoviak.com
adamstacoviak@AS-MBP-i7 [11:44:00] [~/Code/OS/sass/modular-scale] [master]
-> % gem owner -a scott@scottkellum.com modular-scale
Pushing gem to https://rubygems.org...
Owner added successfully.
Pushing gem to https://rubygems.org...
Owners for gem: modular-scale
- scott@scottkellum.com
- mason@canarypromo.com
- adam@adamstacoviak.com
```

**Comment by codingdesigner** [comment]
YES!!! new release this afternoon, @scottkellum 

thanks. @adamstac!!!!!
