### ISSUE TITLE
Problem with rails

### ISSUE THREAD

**Issue by Anahkiasen** [modularscale/modularscale-sass#24]
I can't seem to get this to work with Rails 3.2.6
I put `gem "modular-scale", "~> 0.0.5"` in my Gemfile but when I do `@import "modular-scale"` it throws a file not found error. I've had no problems using it in other frameworks, PHP or whatever, but Rails doesn't seem to find the gem.
Is there something specific to do or is it related to the new incoming gem ?

**Comment by scottkellum** [comment]
Did you put `require 'modular-scale'` in your Compass config file?

If that still doesn’t work, write `gem list` in terminal and see if modular-scale is in that list.

I have run into this issue as well and found writing a .rvmrc file to isolate the ruby environment helps. Just add a file [like this](https://github.com/scottkellum/modular-scale/blob/master/.rvmrc) to your project and you will have a clean Ruby environment.

Let me know if that worked so I can close this issue.

**Comment by Anahkiasen** [comment]
I'm kind of new to Rails, where should I place the require ? In `/config.rb` or `/config/compass.rb` ?

**Comment by scottkellum** [comment]
Your compass project should have a config.rb`file. Add the`require 'modular-scale'` there.

**Comment by batdevis** [comment]
@Anahkiasen , have you resolved the issue? Where is the Compass config file? What's its content?
