### ISSUE TITLE
Trouble getting it working (returns 0px)

### ISSUE THREAD

**Issue by OliverJAsh** [modularscale/modularscale-sass#25]
I have installed the gem and required it in my Compass. The following code:

``` scss
@import "modular-scale";
$ratio: golden();
$scale: modular-scale(1, 16px, $ratio);
@include modular-scale-list(1, 3, 16px, $ratio);
@debug $scale;
```

Produces:

```
/Library/Ruby/Gems/1.8/gems/modular-scale-1.0.0/stylesheets/_modular-scale.sass:209 DEBUG: MS-LIST: 0px 0px 0px
/Users/Oliver/Development/Static/OliverJAsh/source/_scss/base.scss:34 DEBUG: 0px
overwrite source/css/base.css 
```

Have I missed something? I have the previous version of the gem but ran `sudo gem install modular-scale` again and it appeared to update.

**Comment by codingdesigner** [comment]
I think my code makes some assumptions about sassy-math that are wrong now. I'll dive in soon.

**Comment by codingdesigner** [comment]
I have a temporary fix. Instead of `golden()`, use `golden_ratio()`. I think I just need to create an alias for that ratio. 

``` scss
$ratio: golden_ratio();
$scale: modular-scale(1, 16px, $ratio);
@include modular-scale-list(1, 3, 16px, $ratio);
@debug $scale;
```

returns the expected values.

**Comment by codingdesigner** [comment]
try updating the gem. I think I have this fixed.

**Comment by OliverJAsh** [comment]
Updating works. Thank you!

Oliver
