### ISSUE TITLE
Sass 3.2.0 causes errors

### ISSUE THREAD

**Issue by drejohnson** [modularscale/modularscale-sass#26]
When updating to sass 3.2.0 I get a error like this in my stylesheets: 'error sass/app.scss (Line 7 of _globals.scss: Function ms is missing argument $base-size.)'

It does give this error on sass version 3.2.0.alpha.278 and below.

**Comment by codingdesigner** [comment]
I just pushed a new gem that should fix this. update to 1.0.2 and let me know if there are still issues.
