### ISSUE TITLE
_modular-scale.sassc: can't dump anonymous class (on rails 4)

### ISSUE THREAD

**Issue by slbug** [modularscale/modularscale-sass#28]
<pre>
Warning. Error encountered while saving cache [RAILS_ROOT]/tmp/cache/sass/c128eee8c8d012fc0634122b270ca80bc0c6c6e5/_modular-scale.sassc: can't dump anonymous class #<Class:0x000000038b46a8>
</pre>

Sample app https://github.com/slbug/test_modular_scale (just start, open localhost:3000, see console)

**Comment by slbug** [comment]
Full stack trace 

<pre>
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/cache_stores/base.rb:51:in `dump'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/cache_stores/base.rb:51:in `store'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/cache_stores/chain.rb:19:in `block in store'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/cache_stores/chain.rb:19:in `each'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/cache_stores/chain.rb:19:in `store'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/engine.rb:353:in `_to_tree'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/engine.rb:274:in `to_tree'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/perform.rb:222:in `visit_import'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/base.rb:37:in `visit'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/perform.rb:98:in `visit'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/base.rb:53:in `map'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/base.rb:53:in `visit_children'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/perform.rb:107:in `block in visit_children'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/perform.rb:119:in `with_environment'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/perform.rb:106:in `visit_children'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/base.rb:37:in `block in visit'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/perform.rb:126:in `visit_root'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/base.rb:37:in `visit'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/perform.rb:98:in `visit'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/visitors/perform.rb:7:in `visit'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/tree/root_node.rb:20:in `render'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/engine.rb:315:in `_render'
~/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.2.1/lib/sass/engine.rb:262:in `render'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/sass-rails-9b60259818a0/lib/sass/rails/template_handlers.rb:106:in `evaluate'
~/.rvm/gems/ruby-1.9.3-p194/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/context.rb:197:in `block in evaluate'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/context.rb:194:in `each'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/context.rb:194:in `evaluate'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/processed_asset.rb:12:in `initialize'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:350:in `new'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:350:in `block in build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:371:in `circular_call_protection'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:349:in `build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/index.rb:93:in `block in build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/caching.rb:58:in `cache_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/index.rb:92:in `build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:270:in `find_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/index.rb:60:in `find_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/processed_asset.rb:105:in `each'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/processed_asset.rb:16:in `initialize'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:350:in `new'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:350:in `block in build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:371:in `circular_call_protection'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:349:in `build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/index.rb:93:in `block in build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/caching.rb:58:in `cache_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/index.rb:92:in `build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:270:in `find_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/index.rb:60:in `find_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/bundled_asset.rb:16:in `initialize'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:353:in `new'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:353:in `build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/index.rb:93:in `block in build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/caching.rb:58:in `cache_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/index.rb:92:in `build_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/base.rb:270:in `find_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/index.rb:60:in `find_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/environment.rb:74:in `find_asset'
~/.rvm/gems/ruby-1.9.3-p194/gems/sprockets-2.5.0/lib/sprockets/server.rb:47:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/journey-1372f0c608b2/lib/journey/router.rb:68:in `block in call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/journey-1372f0c608b2/lib/journey/router.rb:56:in `each'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/journey-1372f0c608b2/lib/journey/router.rb:56:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/routing/route_set.rb:612:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/etag.rb:23:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/conditionalget.rb:25:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/flash.rb:219:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/cookies.rb:345:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/activerecord/lib/active_record/query_cache.rb:34:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/activerecord/lib/active_record/migration.rb:343:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/activesupport/lib/active_support/callbacks.rb:337:in `_run__3942311220296780278__call__callbacks'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/activesupport/lib/active_support/callbacks.rb:74:in `run_callbacks'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/reloader.rb:64:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/remote_ip.rb:36:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:19:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/railties/lib/rails/rack/logger.rb:26:in `call_app'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/railties/lib/rails/rack/logger.rb:16:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/request_id.rb:21:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/runtime.rb:17:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/activesupport/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/lock.rb:15:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/actionpack/lib/action_dispatch/middleware/static.rb:63:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/railties/lib/rails/engine.rb:506:in `call'
~/.rvm/gems/ruby-1.9.3-p194/bundler/gems/rails-08c4eb5e24f2/railties/lib/rails/application.rb:95:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/lock.rb:15:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/content_length.rb:14:in `call'
~/.rvm/gems/ruby-1.9.3-p194/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59:in `service'
~/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
~/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
~/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
</pre>

**Comment by scottkellum** [comment]
Are you experiencing problems importing any other compass plugins? I am not familiar with setting up ruby apps or compass-ruby so this is difficult for me to debug.

I’m also not seeing `require 'modular-scale'` in your config file, but I am not sure where you would put something like this in a Ruby app.

**Comment by slbug** [comment]
any other plugins works well. i've just created this app to check where issue is. zurb-foundation plugin uses modular scale and i see same warning.

**Comment by codingdesigner** [comment]
I also don't work with Ruby apps so it might take a while to debug. I'll look into what the "can't dump anonymous class" error might mean tho. It might also have something to do with Ruby 1.9.3. I'm using 1.8.7 (default version on Macs)

**Comment by scottkellum** [comment]
I have been using it with 1.9.2 and it works fine.

**Comment by slbug** [comment]
Can't test on 1.9.2. Rails 4 requires 1.9.3

**Comment by danielbayerlein** [comment]
After the update from Middleman 3.0.6 to 3.0.7, I do have the same problem.

```
Warning. Error encountered while saving cache ./.sass-cache/d175c599ab343807958701afee8ac8957af15d94/_modular-scale.sassc: can't dump anonymous class #<Class:0x007f97f580fcc0>
```

**Comment by davidbegin** [comment]
I am having this problem right now, and haven't found a solution.

**Comment by beathyate** [comment]
Me neither.

**Comment by scottkellum** [comment]
I haven’t run into the problem yet :(

I am by no means experienced with ruby/rails if anyone knows where we might start or wants to help it would be greatly appreciated.

**Comment by beathyate** [comment]
Maybe this could be it, but I haven't tested yet: https://github.com/rails/rails/blob/3-2-stable/actionpack/actionpack.gemspec#L26

**Comment by danielbayerlein** [comment]
With version 1.0.3, the problem no longer exists for me.

```
Warning. Error encountered while saving cache ./.sass-cache/d175c599ab343807958701afee8ac8957af15d94/_modular-scale.sassc: can't dump anonymous class #<Class:0x007f97f580fcc0>
```

**Comment by davidbegin** [comment]
I upgraded and it solved the problem for me too.

**Comment by scottkellum** [comment]
Really? well thats convenient. awesome.

**Comment by trimentor** [comment]
After upgrading from version 1.0.2 to 1.0.3 I can also confirm that the warning is gone.
