### ISSUE TITLE
Problem with codekit

### ISSUE THREAD

**Issue by saulsolorzano** [modularscale/modularscale-sass#29]
Hi! I've been trying to use your gem, it installs just fine but when I try to require it using codekit (I know I have to use the complete path): require '/Library/Ruby/Gems/1.8/gems/modular-scale-1.0.2/lib/modular-scale.rb';

I keep getting this error:

"Compass was unable to compile one or more files in the project: 

LoadError on line 2 of /Library/Ruby/Gems/1.8/gems/modular-scale-1.0.2/lib/modular-scale.rb: no such file to load -- sassy-math
Run with --trace to see the full backtrace"

I've even installed sassy-math just in case and nothing, I hope you guys can help me here!

Thanks a lot

**Comment by 144288** [comment]
Getting the same thing. Wish I could be more helpful in suggesting a solution!

**Comment by adamstac** [comment]
Do you have the Sassy Math gem installed?

**Comment by adamstac** [comment]
Opps, commented and closed ... then re-opened. My bad.

**Comment by saulsolorzano** [comment]
Yes, I have it installed and have it require in config.rb and nothing

**Comment by 144288** [comment]
Same here - installed and required.

**Comment by adamstac** [comment]
Can you test to see if you use just Sassy Math in the project ...

Meaning, comment out the usage of Modular Scale and try to see if Sassy Math is getting loaded for usage. If not, then there's something wrong with it getting loaded for whatever reason.

**Comment by 144288** [comment]
I _think_ I found all the places I used it and commented out but I still get the error.

**Comment by adamstac** [comment]
Any way you can share your project so I can help troubleshoot? If it's on GitHub add me 'adamstac'

**Comment by saulsolorzano** [comment]
Well, I commented it out and codekit gave me the green light, what to you think may be the problem? I'm not using it in any projects, I wanted to try it first and it gave me the error

**Comment by adamstac** [comment]
Hard to tell really. It's not loading the sassy-math library, so that's where'd I'd start.

**Comment by saulsolorzano** [comment]
Well, I think sassy-math is loading, I'm trying a couple of functions and it works fine, do you know what does this "Run with --trace to see the full backtrace" mean?

**Comment by 144288** [comment]
if you compile with compass in terminal using --trace it will give you a more detailed error log

**Comment by saulsolorzano** [comment]
Ohhh, let me see

**Comment by 144288** [comment]
are you seeing this in your log?

/Library/Ruby/Gems/1.8/gems/sassy-math-1.2/lib/sassy-math.rb:156: warning: already initialized constant VERSION
/Library/Ruby/Gems/1.8/gems/sassy-math-1.2/lib/sassy-math.rb:157: warning: already initialized constant DATE

**Comment by saulsolorzano** [comment]
Yes

**Comment by 144288** [comment]
wonder if that is part of the problem. unfortunately if it is, i don't know what to do about it!

**Comment by saulsolorzano** [comment]
Well, I don't know about you, but if I use compass in the terminal modular-scale works perfect, the problem here is codekit, not modular-scale. Adam! Thank you so much for the help. I'll write Bryan of codekit to see if he knows anything about this. 144288 you can't make it work using the terminal?

**Comment by 144288** [comment]
no I get an error:

Function ms is missing argument $base-size.

**Comment by adamstac** [comment]
I think so as well. Those constants are scoped to the class that contains them.

https://github.com/scottkellum/modular-scale/blob/master/lib/modular-scale.rb#L9
https://github.com/scottkellum/Sassy-math/blob/master/compass/lib/sassy-math.rb#L154

Shouldn't be an issue.

**Comment by 144288** [comment]
looks like other people as seeing the $base-size issue

https://github.com/zurb/foundation/issues/828
https://github.com/zurb/foundation/issues/788

but - I'm not using foundation and I've got the lastest:

sass: 3.2.1
compass: 0.12.2

adam - thanks for your time looking into this. much appreciated

**Comment by rpkoller** [comment]
I think the issue to get modular-scale going with codekit is the following. you've told that compass and modular scale are working fine from the terminal but not if you require it in the compass config.rb file for codekit. i guess you are using the built in compass framework of codekit. codekits compass is considered as external for modular scale so it is unable to reach some necessary dependencies. you have to go to the codekit preferences; there languages->compass ->"use the compass executable at this path" and choose the compass version you've installed manually from the terminal then it should work (the codekit dev told me).  i got susy going with it  (by just using the latest uncompiled files susy project files out of its git repository and linking it by require). as a side note sassy math as well as modular scale dont work that way. i suppose i have to install those two from the terminal (but dont know exactly why). hope the first part helps to get things going. ;)  cheers r.

**Comment by sethburtonhall** [comment]
@rpkoller I am having the same issue, but I have already set "use compass as an executable path".

Has anybody fixed this issue?

**Comment by scottkellum** [comment]
Can you try updating to 1.0.4? This issue may be related to #28 which is fixed.

**Comment by sethburtonhall** [comment]
I updated to 1.0.4, I will post here with any results. Thanks

**Comment by scottkellum** [comment]
@middle8media Any results?

**Comment by sethburtonhall** [comment]
To be honest, I can't remember, too many projects going on. I think I ended up using compass watch in the command line, instead of compiling via Code Kit. So that being said, I never could figure out "use compass as an executable path".

**Comment by torkiljohnsen** [comment]
I had this problem earlier with most (all?) gems like this, and stuff used to be complicated to fix. Had to specify the full path to the gem in config.rb for instance. Nowadays though, this is solved it by setting the Compass executable manually as suggested by @rpkoller:

From the Codekit Preferences, go to Languages and then to Compass.

Under advanced compiler settings, choose "Use the Compass executable at this path", and set the path to your Compass executable. On my system I've set this to `/usr/bin/compass` and stuff works like a charm.

**Comment by torkiljohnsen** [comment]
I just installed modular-scale here and used the aforementioned procedure, and it works as expected.

**Comment by scottkellum** [comment]
Thanks @torkiljohnsen, glad to hear it works. Closing this issue.
