### ISSUE TITLE
Review: new `modular-scale-classes` mixin

### ISSUE THREAD

**Issue by adamstac** [modularscale/modularscale-sass#3]
Hey Scott,

I'm glad Mason got the function in place cause that let me get to this mixin a bit faster. I can see someone defining a scale and using the new [modular-scale-classes](https://github.com/scottkellum/modular-scale/blob/master/stylesheets/_modular-scale.sass#L41) mixin to generate a range of classes to `@extend`. I've built in support for setting the class slug as well as setting the property. Take a peek and let me know what you think and if it can be improved more.

**Comment by adamstac** [comment]
Ok, now we are an official Compass extension with an updated readme as well :) I pushed [the gem](https://rubygems.org/gems/modular-scale) to RubyGems as well.

**Comment by codingdesigner** [comment]
I added some arguments to the modular-scale-classes mixin to give you the ability to control it as precisely as the other mixin and functions.

**Comment by scottkellum** [comment]
Looks good. I think we can close this now.

I think we need to look into the usability of the multiple ratios vs base sizes now: [issue 8](https://github.com/scottkellum/modular-scale/issues/8)
