### ISSUE TITLE
Outputting scales in Terminal

### ISSUE THREAD

**Issue by Soundsauca** [modularscale/modularscale-sass#31]
Hi Scott,

I'm a bit new to compass etc. I've got your gem running, but I can't figure out how to output my current settings to a list in the terminal.

If you can help, that'd be great!

**Comment by scottkellum** [comment]
Sure, just write:

``` scss
@include ms-list($start, $finish);
```

Replace `$start` with where you want the list to start and `$finish` with where you want to end on this list.

Let me know if that doesn’t work.

**Comment by Soundsauca** [comment]
Thanks for that, I type that directly in the terminal - ie: 

@include ms-list (0, 8);

and I get 

-bash: syntax error near unexpected token! I must be doing it wrong!

**Comment by scottkellum** [comment]
Hmm, well if the space between the mixin and the parenthesis is there then that might be it. I don’t have time to do a full debug at the moment though.

**Comment by codingdesigner** [comment]
@ottobyte You don't type that @include directly into the terminal. Add the line Scott posted into your Sass file, and it will output the values in that range to the terminal.

**Comment by Soundsauca** [comment]
Thanks for that!  I'll give that a go. I've just found your survival kit which I'm going to look at.
