### ISSUE TITLE
Different scale for negative multiples

### ISSUE THREAD

**Issue by atadams** [modularscale/modularscale-sass#32]
I love using modular scales but find that, while it works great for increasing sizes from the base size (positive multiples), decreasing sizes (negative multiples) get too small too quick—even with smaller ratios. I need finer control with smaller sizes. I have created a function that allows for a separate ratio for negative multiples. Might this be something that would be useful for others and built into Modular Scale? 

I have simply set a `$ratio-negative` variable and if the multiple is negative, I use this ratio. `$ratio-negative` could default to `$ratio` so this feature wouldn't take affect unless `$ratio-negative` was explicitly set. 

Below is a table showing the difference between having a 1.25 ratio for all numbers and a 1.25 ratio for 0 and greater and 1.125 for negative numbers.

```
            All =        < 0 =
Multiple  1.25 Ratio  1.125 Ratio
========  ==========  ===========
 ms(5)        49          49
 ms(4)        39          39
 ms(3)        31          31
 ms(2)        25          25
 ms(1)        20          20
 ms(0)        16          16
ms(-1)        13          14
ms(-2)        10          13
ms(-3)         8          11
ms(-4)         7          10
ms(-5)         5           9
```

**Comment by codingdesigner** [comment]
This is interesting. It wouldn't be too hard to implement, but I'm not sure we need it. To solve the issue of values being too widely spaced I use either multiple base sizes or multiple ratios, like this:

`$base-size: 16px 44px`
or
`$ratio: golden_ratio() minor-third()`

There's usually no need to have multiples of both variables, but it's possible. 

Does that help? 

I'm thinking about your suggestion, but my first impression is that it breaks the concept of a modular scale a little.

**Comment by scottkellum** [comment]
closing without action.
