### ISSUE TITLE
Modular-scale-list output if Codekit is used

### ISSUE THREAD

**Issue by rpkoller** [modularscale/modularscale-sass#34]
I am running Sass & Compass via Codekit. To be able to use the Modular Scale extension  i had to install Sass & Compass in the terminal and then call the external versions of them from within Codekit. Otherwise they wouldn't work due to dependency issues. So far so good. But my questions is, is there a way to output the mixin modular-scale-list if the preprocessing is done in Codekit - cuz a console output wouldn't be possible if Codekit is running things i suppose? 

And would it be possible to implent an option to print out a "commented out" ms-list to the sass/scss file? 

A mixin offering some kind of Modular Scale summary, like suggested by Tim Brown, would be nice as well :
## /*

Typesetting for ALA
Author:   Tim Brown
Date:     21 Apr 2011

http://modularscale.com/scale/?px1=18&px2=190&ra1=1.618
18px @ 1:1.618
190px @ 1:1.618

http://alistapart.com/articles/more-meaningful-typography/
----------------------------------------------- */

Best regards Ralf

**Comment by scottkellum** [comment]
added https://github.com/scottkellum/modular-scale/commit/1da88e5b2e69f976baa23b4bd5ee60cfbd0daa57
