### ISSUE TITLE
confused on modular-scale-list and modular-scale-classes 

### ISSUE THREAD

**Issue by stoplion** [modularscale/modularscale-sass#36]
Awesome plugin, but I am kind confused on some of the documentation on here. 

---

"You can output a list to your terminal to help you find out what values are on your scale."
`@include modular-scale-list($start, $end, $base-size, $ratio)`

So I can call `+modular-scale-list(1, 12, 16px, $ratio)` in say base.sass and I will see the 1—12 scale numbers flash by in my Bash terminal? 

Or start in the Sass repl `sass -i` and type modular-scale-list(1, 12, 16px, $ratio) and  see the 1—12 scale numbers flash by in my Bash terminal? 

Neither of these are working for me.

---

In this [article](http://thesassway.com/projects/modular-scale) they mention `modular-scale-classes` with class slug variable and all that. I tried this, peeked at my source code and no "ms-1", "ms-2" to be found. I also peeked at your source code and didnt see any `modular-scale-classes` mixins.

Is this feature no longer available? Deprecated? 

---

Thanks!

**Comment by scottkellum** [comment]
they have been deprecated, Feel free to loop your own but it just wasn’t flexable enough or in line with the goals of the project.
