### ISSUE TITLE
Undefined variable "$golden variable" - it was working

### ISSUE THREAD

**Issue by bernardoantunes** [modularscale/modularscale-sass#37]
Hi, I just reinstalled compass and the modular-scale gem.

Everything was working before without any problem. Now it started saying this message and I have no clue.

My site is a simple github page, so you can see what I mean.

https://github.com/bernardoantunes/bernardoantunes.github.com

Any help would be appreciate, I saw the other post about the same problem but I got no solution that worked. Also this is a different problem because it was already working nice and I changed nothing in the code.

**Comment by scottkellum** [comment]
Try `golden()`

We moved the included ratios over to functions.

Let me know if that works so I can close out the issue.

**Comment by bernardoantunes** [comment]
Hi Scott,

It solved the problem. Thank you very much.

Best regards,
Bernardo

Date: Sat, 3 Nov 2012 17:40:45 -0700
