### ISSUE TITLE
Invalid US-ASCII character in _modular-scale.sass

### ISSUE THREAD

**Issue by patrickansari** [modularscale/modularscale-sass#43]
Line 220 of  _modular-scale.sass is causing issue as for some reason the file isnt't interpreted as UTF-8. The offending character is "•". Have commented out the line and it worked, but obviously not a solution.

I'm using rvm with ruby 1.9.3 and Compass 0.12.2,  Sass 3.2.4.

Any tips would be appreciated.

**Comment by scottkellum** [comment]
Hmm, sorry about that. The unicode line should have solved that and you aren’t running through a GUI so not sure why it is choking on it.

I will change it to an ascii char next time I get a chance. For now you can specify `1.0.2` in your gemfile or `gem install modular-scale -v 1.0.2`.

**Comment by patrickansari** [comment]
Thanks, I suspect it's nothing to do with your file actually - more likely some funky encoding issue on my side making it choke on any unicode chars. Seems like a common issue though haven't yet found a good solution. Will keep looking and post what I find.

**Comment by scottkellum** [comment]
fixed in 1.0.4
