### ISSUE TITLE
1.0.5 - Unable to find 'modular-scale' upon @import with compass

### ISSUE THREAD

**Issue by chaffeqa** [modularscale/modularscale-sass#45]
Had to revert to 1.0.2 due to somehow 'modular-scale' not being registered as @import-able for compass...

Can give more info if needed, but jsut wanted to let you know

**Comment by scottkellum** [comment]
crap, thanks, does 1.0.3 or 1.0.4 work for you?

**Comment by HGebhardt** [comment]
Same issue when you are installing the foundation gem (since it's compass based): http://foundation.zurb.com/docs/rails.php
"File to import not found or unreadable: modular-scale."

1.0.4 of your gem is working fine.

**Comment by scottkellum** [comment]
Welp, literally one character changed between 1.0.4 and 1.0.5

time to rebuild the gem :frowning:

**Comment by Genkilabs** [comment]
I just added this to foundation https://github.com/zurb/foundation/issues/1389

**Comment by manuel-woelker** [comment]
Got bit by this as well. It seems the stylesheets folder is simply missing. Reverting to 1.0.4 worked fine.

**Comment by scottkellum** [comment]
Fixed in 1.0.6

**Comment by manuel-woelker** [comment]
Works like a charm, thanks for the quick fix!
