### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#46]
I think there is a lot we can simplify and consolodate here as well as writing more in Ruby.

I started a new branch where I am working on some things. Architecture wise I think we can make this tighter.

```
ms-function($n)
  @if multi-ratio or multi-size
    list: ()
    from 0 - $n
      add each ratio to list
      add each size to list
    sort list, trim list
    return nth list ($n)
  @else
    return basic math
```

This should be faster, easier to read, and more DRY. Hunting down issue #33 is a nightmare in the current iteration.

We should also have the math consolidated in the ruby instead of broken in both ruby and Sass. Starting to explore some here: https://github.com/scottkellum/modular-scale/tree/refactor

**Comment by scottkellum** [comment]
Thinking about not doing this in Ruby, only because Compass isn’t the only front-end package manager these days and there is no way to get this working with lib-sass.

It will be tricky to do this within a performance budget, but then we could push to Compass/Bower/Yeoman/Bourbon/flat-file…

Note foundation dropped modular-scale as they are moving away from Compass as a strict dependency.

**Comment by codingdesigner** [comment]
hmm. It's going to be tricky to keep performance a priority w/o dropping features. I hear you on that reasoning tho. I'll try to think about this this week tho.

**Comment by scottkellum** [comment]
Yeah, dropping too many features.

The major hit is with the lack of exponent support in Sass making non-positive integer values difficult to calculate. That on top of list sorting is too much of a performance hit to recover from. Submitted a feature request to Sass core: https://github.com/nex3/sass/issues/684

I feel like there has to be a way to do list sorting more efficiently in Sass, even toying with ideas around caching to variables to skip a few calculation cycles. At any rate, looks like this has to be in Ruby for now…

**Comment by Soundsauca** [comment]
Sorry if I'm jumping in here, is this the reason why when I use:
    +adjust-font-size-to( ms(-2) , 1)
    +leader( ms(-2), 1)
I get large 'incorrect' spacing as opposed to tighter ones?

**Comment by scottkellum** [comment]
@ottobyte Not this issue in particular, but probably issue #33 If you are using multiple bases or multiple ratios.

**Comment by scottkellum** [comment]
its done
