### ISSUE TITLE
Line 5: Function golden-ratio is missing argument $value.?

### ISSUE THREAD

**Issue by ldexterldesign** [modularscale/modularscale-sass#48]
Hey,

Thanks for your work on this feature - excited to get playing with it ( https://twitter.com/ldexterldesign/status/345131467938091008 ), however I'm getting the following error on start up - any help?

![screen shot 2013-06-13 at 12 00 14](https://f.cloud.github.com/assets/1715809/647958/51b52f20-d419-11e2-9cc7-31e0eb70f840.png)

Yours hopefully,

**Comment by ldexterldesign** [comment]
Ahh, I've just realised you need http://compass-style.org/ for this, correct?

Cheers,

**Comment by floscr** [comment]
I've got the same issue, but only if I also use bourbon.

**Comment by scottkellum** [comment]
You need to use this with Compass

**Comment by scottkellum** [comment]
It says “Compass” in the install process, is that not clear enough?

**Comment by floscr** [comment]
I'm using compass, but i also like to @import bourbon to compass…

**Comment by scottkellum** [comment]
@artish Bourbon has a modular-scale function as well with the same name: http://bourbon.io/docs/#modular-scale

There will definitely be conflicts, try @importing modular-scale _below_ your bourbon import.

Let me know if that helps, reopening until settled

**Comment by floscr** [comment]
Oh gosh! I didn't know that bourbon had a similar function. Sorry about that!

I already have the modular-scale import below the bourbon import and compass passes me an error.

**Comment by scottkellum** [comment]
Looking further into it there is no easy way to fix this as my codebase currently exists. Looks like Bourbon is doing some things with the golden ratio function that aren’t compatible with what I am doing.

You will have to selectively import Bourbon or avoid modular-scale.

Closing without further action.

**Comment by ldexterldesign** [comment]
@artish you can use the Bourbon update here https://github.com/thoughtbot/bourbon/pull/175

Count yourself lucky - I have 3 versions of the modular-scale function in my project ( https://github.com/typeplate/typeplate.github.io/issues/112 )! :(

Best regards,

PS It would be useful if there was a universal modular scale everyone could agree on with:
- Double strand
- rem output/px fallback
