### ISSUE TITLE
sort-list posing problem

### ISSUE THREAD

**Issue by mnakalay** [modularscale/modularscale-sass#51]
Hello,
Totzl ruby / sass / compass newbie here.

I am trying to use modular-scale.
I am not installing the gem or anything. I tried but it didn't seem to work for some reason but that's not the issue.
I installed sassy-math (the gem) and I'm importing modular-scale directly in my scss file
I keep getting problems with the compiler complaining about the sort-list function not being defined.

In an old version of modular scale that function was included but it's not anymore.
I also can't find it anywhere in sassy-math.

I just can't figure it out. Could you help me please?

**Comment by scottkellum** [comment]
Please follow all the [installation instructions](https://github.com/Team-Sass/modular-scale#installation). You need to install the gem and use it with Compass.
