### ISSUE TITLE
Using ems instead of pixels

### ISSUE THREAD

**Issue by Soundsauca** [modularscale/modularscale-sass#52]
Hi, I want to output ems instead of pixels. I've tried setting `$base-size: 1em` however Compass doesn't like this.

**Comment by scottkellum** [comment]
Should work fine, I use ems all the time: http://sassmeister.com/gist/6082041

**Comment by Soundsauca** [comment]
Thanks for that, that seems to work!

**Comment by Soundsauca** [comment]
Sorry, yes it works in that instance, I have been attempting to use it like this '`+adjust-font-size-to( ms(2) , 2  )`, I'm getting `error sass/style.sass (Line 99 of _vertical_rhythm.scss: 0.265em*em/px isn't a valid CSS value.)` as a result. Does modular-scale not work with Compass this way?

Many thanks Scott

**Comment by scottkellum** [comment]
ah, yeah vertical rhythm only works with px. It’s an issue with the vertical rhythm module in Compass, not an issue with Modular Scale.

Hopefully they will get it to work with ems although vertical rhythm tends to work better in pixels. I don’t usually use Compass vertical rhythm so I don’t really bother with.

**Comment by Soundsauca** [comment]
Right I'm with you, thanks a lot for clearing that one up Scott,

Would you say just directly using the ms() functions directly on the font-size, margins etc is the way to go?

**Comment by scottkellum** [comment]
@ottobyte Yes! I use `ms()` _everywhere_ in my personal projects. Breakpoints, margins, everywhere.
