### ISSUE TITLE
modular-scale background

### ISSUE THREAD

**Issue by jasonkendall** [modularscale/modularscale-sass#53]
Is there a way to show a ms background like, for instance, the way we can turn on a SUSY grid background? You know, sort of like the horizontal rules on a piece of notebook paper.

Thanks!

**Comment by scottkellum** [comment]
This is not within the scope of modular-scale but you may want to check out [Singularity](https://github.com/Team-Sass/Singularity/) and use the [background-grid](https://github.com/Team-Sass/Singularity/wiki/Creating-Grids#visualizing-your-grids) mixin.
