### ISSUE TITLE
Create and maintain a changelog

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#55]
Good example: https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.rdoc

**Comment by ap4y** [comment]
Hey, can you also assign `git tag` (`github release`) for versions of the `modular-scale`. There is a `bower.json` in this project, unfortunately `bower` gets library version from `git tag`, so latest version for `modular-scale` in `bower` is only `0.0.4`. Thanks!

**Comment by scottkellum** [comment]
done
