### ISSUE TITLE
Undefined operation: Infinity times for perfect-fourth()

### ISSUE THREAD

**Issue by ghost** [modularscale/modularscale-sass#57]
The error I get is:

Syntax error: Undefined operation: "Infinity times 16px 78px".
on line 52 of /home/rajib/.rvm/gems/ruby-1.9.3-p392/gems/modular-scale-1.0.6/stylesheets/_modular-scale.scss

The sass code I am calling from is:

$ratio: perfect-fourth();
$base-font-size: 16px !default;
$importantNum: 78px !default;
$base-size: $base-font-size $importantNum;

Instead of perfect-fourth() if I use golden() then its working properly.

**Comment by scottkellum** [comment]
[Should be fixed in 2.0](https://github.com/Team-Sass/modular-scale/blob/2.x/readme.md). Please reopen if it isn’t.
