### ISSUE TITLE
Bower installs wrong version?

### ISSUE THREAD

**Issue by ellioseven** [modularscale/modularscale-sass#59]
When I run:

<code>bower install modular-scale</code>

It shows installs 0.0.4, and I can't seem to get 1.0.6?

If I run:

<code>bower info modular-scale</code>

I get:

<pre>cached git://github.com/Team-Sass/modular-scale.git#0.0.4
validate 0.0.4 against git://github.com/Team-Sass/modular-scale.git#*
</pre>

I have just started using git & bower so maybe I am doing it wrong, but it seems like I am getting the wrong version?

**Comment by scottkellum** [comment]
Bower is now on v2 which is not documented but far easier to deal with. Will update docs soon.
