### ISSUE TITLE
Would it make sense to be able to create more than one scale for a single project?

### ISSUE THREAD

**Issue by rpkoller** [modularscale/modularscale-sass#61]
I am playing around with the combo modular scale alongside the compass vertical rhythm module. If you would like to try to apply different base sizes like on the ia.net homepage with a  small base size for small viewports and a larger base size for desktop sized viewports i ask myself two questions: 
- If you try to build a layout like the ia.net page with a single scale it would be like ms(-1) (or a even lower value) on mobile for the p element and for desktop viewports ms(0) and the adjustment on other typography related elements accordingly? 
- Or would it make a noticeable visual impact if you define a scale for mobile viewports and a second for desktop viewports; so that you would be able to establish different scales on different viewports in compass vertical rhythm module. I am just unsure if it would make a noticeable difference and thinking it through makes my head spin pretty much. ;))) But if it would i might have an idea for the vertical rhythm side how to take advantage of it - might give a patch a try then too. 

Best regards r.

**Comment by scottkellum** [comment]
@rpkoller I don’t actually use Compass vertical rhythm but modular scale is calculated on the fly so you could easily do ms(0, 12px) for smaller viewports and ms(0, 16px) for larger viewports.

A better solution might be to use ems or rems in your layout which allows you to scale everything by changing the `font-size` on the `html` element. This works really well with modular scale but I don’t think the vertical rhythm module has support for either of these units.

**Comment by rpkoller** [comment]
Played a little around with it and i guess everything seems already work outside of the box.  http://sassmeister.com/gist/7992795 . The only thing not working is on the compass side that if you are defining two baselines that it might have issues to stick to the right one. in my example the values for the 750px breakpoint get applied to the base one. But aside that things seems to work flawless. I am even able to define more than one modular scale (the values used are just for test purpose - nothing serious). And yep as you can see Vertical Rhythm is using ems by default. Cheers Ralf
