### ISSUE TITLE
defaults that allow easy user override.

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#7]
It is more important to allow the user to set the defaults, but I understand the importance of defaults being baked in. The nature of the cascade makes this hard to do as a standalone file.

**Comment by codingdesigner** [comment]
Ahh, just did some testing on this. You can set default values before defining the function or mixin like we had before, but the problem you found was an error in the example sass file. The were setting new !default values, but were being ignored. The solution is to just set a new value to the variable. Like so:

## _modular-scale.sass

```
$ratio: $golden !default
$base-size: 12px !default
$property: font-size !default
$class-slug: ms !default

// Modular Scale function
@function modular-scale($multiple, $base-size, $ratio)
```

## example.sass

```
.foo
  width: modular-scale(2)
// $base-size value is 12px

$base-size: 14px

.bar
  width: modular-scale(2)
// $base-size value is 14px

$base-size: 16px !default

.baz
  width: modular-scale(2)
// $base-size value is 14px
```

This solves the problem. I'll push the code for this today.

**Comment by codingdesigner** [comment]
pushed some code: 
- add default values back. fix the redeclared defaults in the test sass file
- organize the example sass file
- removing the duplicate test html and css. Went with the server version because I find it useful, and because that's the way the config.rb file was set up

**Comment by scottkellum** [comment]
nice, why use .html.erb though?

**Comment by codingdesigner** [comment]
mostly because it was working with Serve. I think its moderately helpful while developing. not a dealbreaker for me if you feel like simplifying that tho.

**Comment by scottkellum** [comment]
ah, that makes sense. We can leave it as-is for now but in the long run I would like everything as bare-bones simple as possible.
