### ISSUE TITLE
[enhancement] Add missing bower.json.

### ISSUE THREAD

**Issue by timgluz** [modularscale/modularscale-sass#71]
#### Hey, maintainer(s) of Team-Sass/modular-scale!

We at [VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) are working hard to keep up the quality of the bower's registry.

We just finished our initial analysis of the quality of the Bower.io registry:

**7530** - registered packages, _224_ of them doesnt exists anymore;

We analysed **7306**  existing packages and  **1070** of them don't have bower.json on the master branch ( _that's where a Bower client pulls a data_ ).

Sadly, your library `Team-Sass/modular-scale` is one of them.

Can you spare **15** minutes to help us to make Bower better?

Just add a new file `bower.json` and  change attributes.

```
{
  "name": "Team-Sass/modular-scale",
  "version": "1.0.0",
  "main": "path/to/main.css",
  "description": "please add it",
  "license": "Eclipse",
  "ignore": [
    ".jshintrc",
    "**/*.txt"
  ],
  "dependencies": {
    "<dependency_name>": "<semantic_version>",
    "<dependency_name>": "<Local_folder>",
    "<dependency_name>": "<package>"
  },
  "devDependencies": {
    "<test-framework-name>": "<version>"
  }
}

```

Read more about bower.json [on the official spefication](http://bower.io/#defining-a-package) and nodejs [semver](https://github.com/isaacs/node-semver#ranges) library has great examples of proper versioning.

**NB!** Please _validate_ your bower.json with _jsonlint_ before commiting your updates.

Thank you!

Timo,
twitter: @versioneye
email: timo@versioneye.com
[VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) - no more legacy software!

**Comment by scottkellum** [comment]
@timgluz This should be resolved now. Can you please add to the Bower docs that the branch in question must be the master. The default branch here was “2.0” not “master” and according to the Bower docs, Bower looks at the origin, not the “master” branch.

I made the naming changes here and created a new issue for you on Bower github: https://github.com/bower/bower/issues/1035

**Comment by timgluz** [comment]
Thanks.

default branch doesnt has to be `master` - it was my mistake - github resolves default_branch correctly and this isnt actually problem;
