### ISSUE TITLE
"golden()" is not a number for `pow'

### ISSUE THREAD

**Issue by perceptbe** [modularscale/modularscale-sass#76]
I'm experimenting with modular-scale and I'm running in to trouble ...

I included modular-scale, defined the required variables

``` sass
$ms-base: 1em;
$ms-ratio: golden();  -> took me a while since the docs say "$golden" instead of "golden()"
```

but when I add 

``` sass
h1 {
  font-size: ms(4);
}
```

I get the following error:

error sass/my.styles.scss (Line 9 of _calc.scss: "golden()" is not a number for `pow')

What am I missing here?

**Comment by scottkellum** [comment]
What version of modular scale are you running? Did you install this via the gem or copy and paste the SCSS into your project?

**Comment by pastinepolenta** [comment]
Same here. Installed via gem. "gem list" shows:
modular-scale (2.0.4, 1.0.6)

and after "gem cleanup modular-scale" I have only the 2.0.4 and the error is still there

Sorry , my bad. I was still using golden() instead of $golden in some of my sass files.

**Comment by scottkellum** [comment]
Thanks @stilllife00.

@percept- Can you follow these [upgrade instructions](https://github.com/Team-Sass/modular-scale#upgrading-from-1x-to-2x) and let me know if that fixes your issue?

**Comment by perceptbe** [comment]
@scottkellum Installed via gem. "gem list" showed
modular-scale (2.0.0.alpha5, 1.0.6)

now it's fine with only the 2.0.0.alpha5
