### ISSUE TITLE
custom ratio causes compass watch to hang

### ISSUE THREAD

**Issue by equivalentideas** [modularscale/modularscale-sass#79]
When I use a custom variable Compass says the file was modified, then does not resolve to an error or compilation.

```
$ms-base: 16 18;

$my-ratio: 1 / 3.14159265;
$ms-ratio: $my-ratio;

@debug ms-list(1, 5, $ms-base, $ms-ratio);
```
## Gemfile

```
source "https://rubygems.org"

gem "sass", "~>3.3.2"
gem "compass", "~>1.0.0.alpha.17"
gem "singularitygs", "~>1.2.0"
gem "modular-scale", "~>2.0.4"
```

**Comment by scottkellum** [comment]
try `$my-ratio: (1 / 3.14159265);`

**Comment by equivalentideas** [comment]
Doesn't help unfortunately.

**Comment by scottkellum** [comment]
You need a ratio greater than 1. I will keep this open to check and inverse the ratio if it is less than 1.

**Comment by scottkellum** [comment]
You ratio should be `3.14159265`.
