### ISSUE TITLE
dual base-sizes instead of dual ratios

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#8]
Tim's modular scale uses dual base-sizes instead of dual ratios.
http://modularscale.com/

Playing around with dual ratios the ratio closer to 1 usually takes precedent over the more extreme ratio.

We can either re-write it so that we support multiple base-sizes or support both multiple base-sizes and multiple ratios. The logic required will grow exponentially if we choose to support both.

Mason, it was your addition, how do you feel about it?

**Comment by codingdesigner** [comment]
yeah now you mention it I realize I flipped it around. To be honest I kind of like this logic better so I'm reluctant to toss it. It's more "musical", like building chords of increasing complexity. But I do like both approaches. 

### To your first point:

What's happening is that all the values are calculated for each ratio, and then all of them are sorted into numeric order. If the two ratios are very far apart then you would see more values from the small one, and then the larger one would kick in. 

### Now for supporting multiple base sizes:

This in and of itself is a trickier logic problem. With one base size we simply need to calculate  the nth exponent and then we get to stop. Once there are two or more we need to calculate a wide range, and then blend the sets, and then pluck our answer. Some of that work is very similar to what I did before, but we run into an interesting fundamental problem that I want to think about first: 

Currently to calculate _n_ we just start from our base size and go up or down. 

```
$base-size: 12px
ms(3)
```

We simply start as 12px and go up. But if we have: 

```
$base-size: 12px 100px
ms(3)
```

What number do we go up from? I think the most logical answer is 0, but that may only be logical to me. Let me know what you think.

### solution

I'd like to support both. I think it's possible, and while it is an exponential increase in logic, I think it's the last one we're likely to need. This would let people use it either (or both!) ways, and make it all the more powerful.

**Comment by scottkellum** [comment]
Awesome. I will probably have time Sunday to dig into at least refining the logic for this.

**Comment by codingdesigner** [comment]
I may be able to carve a little time into my day today for a pass at this, otherwise I'll be able to work on it this weekend too.

**Comment by codingdesigner** [comment]
Upon further reflection, I don't thing the central number should be 0. If we did that then every ms(-1) would be a negative number, and it would be unintuitive and unpredictable how many $multiples it would take to get a similar result than if you're using a single $base-size. 

I'd like there to be a similar mental model for using single or multiple $base-size values. 

Therefore I think I'll base my central pivot point on the **lowest** value entered as one of the multiple $base-sizes

**Comment by scottkellum** [comment]
Your sorting logic is a bit beyond me ;)

I cleaned up the calculation logic though, while adding exponents to Sass, which may be helpful outside of the modular scale. https://github.com/scottkellum/modular-scale/blob/sk-dev/stylesheets/_modular-scale.sass

Going to clear my head, then come back to this but feel free to jump back in. Definitely your area of expertise.

**Comment by codingdesigner** [comment]
I just committed a working version with support for multiple base sizes and/or multiple ratios. There's a lot of repeated code that I needed to keep it straight in my head while writing so I haven't committed it to master. I'm going to clean that up and try to integrate your new exponent logic. 

https://github.com/scottkellum/modular-scale/blob/mult-base/stylesheets/_modular-scale.sass

**Comment by codingdesigner** [comment]
Alright. The latest commit has all the features and permutations working for me, and I've cleaned up the code to make it more readable. I added examples to the example sass too. It's late. I'll look at this tomorrow, and would welcome a code review when you get a chance. 

Nice work on that exponent function btw. That's really smooth stuff!

**Comment by scottkellum** [comment]
Nice! This is looking really amazing.
