### ISSUE TITLE
Mismatch betweet git tag and bower.json version numbers

### ISSUE THREAD

**Issue by jdhoek** [modularscale/modularscale-sass#80]
Git tag `v2.0.5` points to a `bower.json` that says `"version": "2.0.3",`. This causes bower to issue a warning about this mismatch when installing modular-scale with `bower install --save modular-scale`.

Could you update `bower.json`'s version for future releases?

**Comment by jdhoek** [comment]
Also, git tag `2.0.4` should be `v2.0.4`.

**Comment by scottkellum** [comment]
thanks, updated bower.json to the latest version

**Comment by jdhoek** [comment]
My apologies, it seems my comment about the git tags wasn't entirely clear and caused you some confusion. With `v2.0.4` I was referring to the git tags in this repository, as they are used by Bower to resolve versions. After that Bower downloads the tagged commit, and reads it `bower.json`.

In `bower.json` the version number should read `2.0.5` (customarily without the `v`, although it works with it as well). So `"version": "2.0.5"` is correct in `bower.json`.

In the git repository, the git tags should always be prefixed with a `v`, so `v2.0.5`. I would recommend removing git tags `2.0.4` and `2.0.5` in favour of `v2.0.4` and `v2.0.5`.

![tags](https://cloud.githubusercontent.com/assets/683699/3141146/904cc666-e968-11e3-9a57-56586ec374d1.png)

**Comment by jdhoek** [comment]
By the way, the modular-scale SASS works great. Nice to have this available from Bower.

**Comment by scottkellum** [comment]
Thanks for bearing with me @jdhoek. It’s probably pretty obvious I don’t actually use Bower.

I removed `2.0.5` and `2.0.4`. From your latest comment I assume the `v` is implied in the `bower.json`. In future releases I will remove it.

**Comment by jdhoek** [comment]
My pleasure.

In Bower the version field is read with NPM's `semver` package, which accepts version numbers with `v` as well as without, but most packages I've come across (like `jquery` etc.) do without the `v`. It's probably all right to use `v2.6.0` in `bower.json` as well, just unconventional.
