### ISSUE TITLE
Explore ways to refine logic

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#9]
Figure out ways to consolidate and refine logic. Building support for exponents may help here. Seems like the calculation loop can be written in once and pulled in as needed.

``` sass
// Sass exponent support
@function exponent($base, $exponenet)
  @if $base > 0
    @for $i from 0 through ($exponenet - 2)
      $base: $base * $base
  @if $base < 0
    @for $i from 0 through ($exponenet + 2)
      $base: $base / $base
  @return ($base)
```

**Comment by codingdesigner** [comment]
Yes. We'll need this. Or something like it if we decide to support multiple base-sizes.

**Comment by codingdesigner** [comment]
I just committed a pass at this. I needed to do it before working on the multiple $base-size value. code review welcome

**Comment by scottkellum** [comment]
revised exponents. now all you need to do is write the following to do the calculation bits:

``` Sass
exponent($ratio, $multiple) * $base-size
```

function here:
https://gist.github.com/1160816

No more splitting up positive and negative multiples. I just need to integrate and push.

**Comment by codingdesigner** [comment]
this looks nice and clean. I'm trying to wrap my head around it. As soon as I do I'll try integrating my new work and this.
