### ISSUE TITLE
Any plans of publishing to NPM?

### ISSUE THREAD

**Issue by sondr3** [modularscale/modularscale-sass#90]
I've started moving most of my front-end packages towards NPM instead of Bower and have found most of them there but modularscale-sass isn't available there, are there any plans to publish there?

**Comment by scottkellum** [comment]
@sondr3 No, but if you shoot me a PR with details on how you want this to work I’ll definitely consider it. Unfortunately there are a lot of distribution channels. I’ll add the channels I know and use but I need to lean on the community to help if they want other distribution channels.

**Comment by sondr3** [comment]
I'll take a look the next few days.

**Comment by scottkellum** [comment]
Leaving this here as an awesome PR that adds NPM https://github.com/yurivictor/typebetter/pull/10

**Comment by scottkellum** [comment]
@sondr3 does this work for you? https://github.com/modularscale/modularscale-sass#eyeglass
