### ISSUE TITLE
Rounding on some smaller values doesn't seem to be right

### ISSUE THREAD

**Issue by fstorr** [modularscale/modularscale-sass#92]
Have a look at this scale: http://www.modularscale.com/?14,50&px&1.333&web&table Once you get lower than 7.879px the last 4 values are the same. I re-did the scale in Excel and got different results:

![modular scale in Excel showing different values from the ones generated on modularscale.com](https://cloud.githubusercontent.com/assets/169471/6629755/c77d501a-c8ce-11e4-88d6-47ae71529926.png)

I've tried different ratios with the same values and these smaller values often don't seem to be quite right.

**Comment by scottkellum** [comment]
Thanks @fstorr, just to be clear this is a bug on the website modularscale.com? Is this also a bug on modularscale-sass?

**Comment by fstorr** [comment]
Dang. My bad—sorry. It's the site, not the Sass plugin.
