### ISSUE TITLE
File to import not found in Rails 4

### ISSUE THREAD

**Issue by donpinkus** [modularscale/modularscale-sass#98]
I'm trying to use the modular scale gem with Rails 4.  However, after adding `@import 'modular-scale';` I get the error `File to import not found or unreadable: modular-scale.`
1. Add `gem "modular-scale"` to gemfile.rb
2. Run `$ bundle install`. Make sure gem is installed.
3. Add `@import 'modular-scale';` to application.css.scss

Are there other steps that need to happen when setting it up on Rails?

**Comment by scottkellum** [comment]
Are you using Compass with Rails 4? `require 'modular-scale'` should be added to your Compass config. If you are not using Compass I recommend using vanilla Sass install method: https://github.com/modularscale/modularscale-sass#vanilla-sass
